import { Food } from '@/types';

export const foodDatabase: Food[] = [
  // 谷物类
  {
    id: '1',
    name: '米饭',
    nameEn: 'Steamed Rice',
    calories: 116,
    protein: 2.6,
    carbs: 25,
    fat: 0.3,
    category: 'grain',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '2',
    name: '燕麦片',
    nameEn: 'Oatmeal',
    calories: 389,
    protein: 16.9,
    carbs: 66,
    fat: 6.9,
    category: 'grain',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '3',
    name: '全麦面包',
    nameEn: 'Whole Wheat Bread',
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    category: 'grain',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '4',
    name: '意大利面',
    nameEn: 'Pasta',
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    category: 'grain',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '5',
    name: '红薯',
    nameEn: 'Sweet Potato',
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    category: 'grain',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '6',
    name: '玉米',
    nameEn: 'Corn',
    calories: 106,
    protein: 3.2,
    carbs: 25,
    fat: 1.2,
    category: 'grain',
    servingSize: 100,
    servingUnit: 'g',
  },
  
  // 蔬菜类
  {
    id: '10',
    name: '西兰花',
    nameEn: 'Broccoli',
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    category: 'vegetable',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '11',
    name: '菠菜',
    nameEn: 'Spinach',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    category: 'vegetable',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '12',
    name: '胡萝卜',
    nameEn: 'Carrot',
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    category: 'vegetable',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '13',
    name: '西红柿',
    nameEn: 'Tomato',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    category: 'vegetable',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '14',
    name: '黄瓜',
    nameEn: 'Cucumber',
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    category: 'vegetable',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '15',
    name: '生菜',
    nameEn: 'Lettuce',
    calories: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    category: 'vegetable',
    servingSize: 100,
    servingUnit: 'g',
  },
  
  // 水果类
  {
    id: '20',
    name: '苹果',
    nameEn: 'Apple',
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    category: 'fruit',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '21',
    name: '香蕉',
    nameEn: 'Banana',
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    category: 'fruit',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '22',
    name: '橙子',
    nameEn: 'Orange',
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    category: 'fruit',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '23',
    name: '蓝莓',
    nameEn: 'Blueberry',
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
    category: 'fruit',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '24',
    name: '草莓',
    nameEn: 'Strawberry',
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    category: 'fruit',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '25',
    name: '牛油果',
    nameEn: 'Avocado',
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 15,
    category: 'fruit',
    servingSize: 100,
    servingUnit: 'g',
  },
  
  // 肉类
  {
    id: '30',
    name: '鸡胸肉',
    nameEn: 'Chicken Breast',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    category: 'meat',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '31',
    name: '牛肉',
    nameEn: 'Beef',
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 17,
    category: 'meat',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '32',
    name: '猪瘦肉',
    nameEn: 'Lean Pork',
    calories: 143,
    protein: 26,
    carbs: 0,
    fat: 3.5,
    category: 'meat',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '33',
    name: '火腿',
    nameEn: 'Ham',
    calories: 145,
    protein: 21,
    carbs: 1.5,
    fat: 6,
    category: 'meat',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '34',
    name: '培根',
    nameEn: 'Bacon',
    calories: 541,
    protein: 37,
    carbs: 1.4,
    fat: 42,
    category: 'meat',
    servingSize: 100,
    servingUnit: 'g',
  },
  
  // 海鲜类
  {
    id: '40',
    name: '三文鱼',
    nameEn: 'Salmon',
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    category: 'seafood',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '41',
    name: '虾',
    nameEn: 'Shrimp',
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
    category: 'seafood',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '42',
    name: '金枪鱼',
    nameEn: 'Tuna',
    calories: 132,
    protein: 28,
    carbs: 0,
    fat: 1,
    category: 'seafood',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '43',
    name: '鳕鱼',
    nameEn: 'Cod',
    calories: 82,
    protein: 18,
    carbs: 0,
    fat: 0.7,
    category: 'seafood',
    servingSize: 100,
    servingUnit: 'g',
  },
  
  // 乳制品
  {
    id: '50',
    name: '牛奶',
    nameEn: 'Milk',
    calories: 42,
    protein: 3.4,
    carbs: 5,
    fat: 1,
    category: 'dairy',
    servingSize: 100,
    servingUnit: 'ml',
  },
  {
    id: '51',
    name: '希腊酸奶',
    nameEn: 'Greek Yogurt',
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    category: 'dairy',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '52',
    name: '奶酪',
    nameEn: 'Cheese',
    calories: 402,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    category: 'dairy',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '53',
    name: '黄油',
    nameEn: 'Butter',
    calories: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81,
    category: 'dairy',
    servingSize: 100,
    servingUnit: 'g',
  },
  
  // 蛋类
  {
    id: '60',
    name: '鸡蛋',
    nameEn: 'Egg',
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    category: 'egg',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '61',
    name: '蛋白',
    nameEn: 'Egg White',
    calories: 52,
    protein: 11,
    carbs: 0.7,
    fat: 0.2,
    category: 'egg',
    servingSize: 100,
    servingUnit: 'g',
  },
  
  // 零食类
  {
    id: '70',
    name: '杏仁',
    nameEn: 'Almonds',
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    category: 'snack',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '71',
    name: '核桃',
    nameEn: 'Walnuts',
    calories: 654,
    protein: 15,
    carbs: 14,
    fat: 65,
    category: 'snack',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '72',
    name: '黑巧克力',
    nameEn: 'Dark Chocolate',
    calories: 546,
    protein: 4.9,
    carbs: 61,
    fat: 31,
    category: 'snack',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '73',
    name: '薯片',
    nameEn: 'Potato Chips',
    calories: 536,
    protein: 7,
    carbs: 53,
    fat: 35,
    category: 'snack',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '74',
    name: '饼干',
    nameEn: 'Biscuit',
    calories: 502,
    protein: 7,
    carbs: 64,
    fat: 25,
    category: 'snack',
    servingSize: 100,
    servingUnit: 'g',
  },
  
  // 饮品类
  {
    id: '80',
    name: '水',
    nameEn: 'Water',
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    category: 'beverage',
    servingSize: 100,
    servingUnit: 'ml',
  },
  {
    id: '81',
    name: '黑咖啡',
    nameEn: 'Black Coffee',
    calories: 2,
    protein: 0.3,
    carbs: 0,
    fat: 0,
    category: 'beverage',
    servingSize: 100,
    servingUnit: 'ml',
  },
  {
    id: '82',
    name: '绿茶',
    nameEn: 'Green Tea',
    calories: 1,
    protein: 0.2,
    carbs: 0.2,
    fat: 0,
    category: 'beverage',
    servingSize: 100,
    servingUnit: 'ml',
  },
  {
    id: '83',
    name: '橙汁',
    nameEn: 'Orange Juice',
    calories: 45,
    protein: 0.7,
    carbs: 10,
    fat: 0.2,
    category: 'beverage',
    servingSize: 100,
    servingUnit: 'ml',
  },
  {
    id: '84',
    name: '可乐',
    nameEn: 'Cola',
    calories: 42,
    protein: 0,
    carbs: 11,
    fat: 0,
    category: 'beverage',
    servingSize: 100,
    servingUnit: 'ml',
  },
  {
    id: '85',
    name: '啤酒',
    nameEn: 'Beer',
    calories: 43,
    protein: 0.5,
    carbs: 3.6,
    fat: 0,
    category: 'beverage',
    servingSize: 100,
    servingUnit: 'ml',
  },
  
  // 其他
  {
    id: '90',
    name: '橄榄油',
    nameEn: 'Olive Oil',
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    category: 'other',
    servingSize: 100,
    servingUnit: 'ml',
  },
  {
    id: '91',
    name: '蜂蜜',
    nameEn: 'Honey',
    calories: 304,
    protein: 0.3,
    carbs: 82,
    fat: 0,
    category: 'other',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '92',
    name: '花生酱',
    nameEn: 'Peanut Butter',
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    category: 'other',
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: '93',
    name: '豆腐',
    nameEn: 'Tofu',
    calories: 76,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
    category: 'other',
    servingSize: 100,
    servingUnit: 'g',
  },
];

export function searchFoods(query: string, locale: string = 'zh'): Food[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return [];
  
  return foodDatabase.filter(food => {
    const nameMatch = locale === 'zh' 
      ? food.name.toLowerCase().includes(lowerQuery)
      : food.nameEn.toLowerCase().includes(lowerQuery);
    const nameEnMatch = food.nameEn.toLowerCase().includes(lowerQuery);
    return nameMatch || nameEnMatch;
  });
}

export function getFoodsByCategory(category: string): Food[] {
  return foodDatabase.filter(food => food.category === category);
}

export function getFoodById(id: string): Food | undefined {
  return foodDatabase.find(food => food.id === id);
}

export function getCategoryLabel(category: string, locale: string = 'zh'): string {
  const labels: Record<string, { zh: string; en: string }> = {
    grain: { zh: '谷物', en: 'Grains' },
    vegetable: { zh: '蔬菜', en: 'Vegetables' },
    fruit: { zh: '水果', en: 'Fruits' },
    meat: { zh: '肉类', en: 'Meat' },
    seafood: { zh: '海鲜', en: 'Seafood' },
    dairy: { zh: '乳制品', en: 'Dairy' },
    egg: { zh: '蛋类', en: 'Eggs' },
    snack: { zh: '零食', en: 'Snacks' },
    beverage: { zh: '饮品', en: 'Beverages' },
    other: { zh: '其他', en: 'Others' },
  };
  return labels[category]?.[locale as 'zh' | 'en'] || category;
}

export const categories = [
  'grain',
  'vegetable',
  'fruit',
  'meat',
  'seafood',
  'dairy',
  'egg',
  'snack',
  'beverage',
  'other',
];
